### ISSUE TITLE
画面に何も表示されない

### ISSUE THREAD

**Issue by denkiuo604** [denkiuo604/ichitabi-timer#6]
**不具合・バグ詳細 (Describe the bug)**
Ichitabi Timerを開いても、画面に何ひとつ表示されない

**再現方法 (To Reproduce)**
Ichitabi Timerを閲覧する

**期待される動作 (Expected behavior)**
Ichitabi Timerが表示される

**スクリーンショット (Screenshots)**
文字通り過ぎてもはや無意味まである

![image](https://github.com/denkiuo604/ichitabi-timer/assets/56901711/97ce46b9-15d3-4655-b41e-82c53c0ed99c)

**端末情報**
任意の端末

**Comment by denkiuo604** [comment]
コンソールに出力されていたエラー
```
TypeError: Cannot read properties of undefined (reading 'getTime')
    at T (index-b5774f22.js:40:65641)
    at index-b5774f22.js:40:65961
    at Array.forEach (<anonymous>)
    at index-b5774f22.js:40:65924
    at Array.forEach (<anonymous>)
    at pe (index-b5774f22.js:40:65909)
    at X0 (index-b5774f22.js:40:64928)
    at Ei (index-b5774f22.js:38:19478)
    at sc (index-b5774f22.js:40:43744)
    at oc (index-b5774f22.js:40:39542)
Lo @ index-b5774f22.js:40
Aa.n.callback @ index-b5774f22.js:40
xu @ index-b5774f22.js:38
Au @ index-b5774f22.js:40
tc @ index-b5774f22.js:40
C0 @ index-b5774f22.js:40
L0 @ index-b5774f22.js:40
Nt @ index-b5774f22.js:40
nc @ index-b5774f22.js:40
E @ index-b5774f22.js:25
tt @ index-b5774f22.js:25
index-b5774f22.js:40  Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')
    at T (index-b5774f22.js:40:65641)
    at index-b5774f22.js:40:65961
    at Array.forEach (<anonymous>)
    at index-b5774f22.js:40:65924
    at Array.forEach (<anonymous>)
    at pe (index-b5774f22.js:40:65909)
    at X0 (index-b5774f22.js:40:64928)
    at Ei (index-b5774f22.js:38:19478)
    at sc (index-b5774f22.js:40:43744)
    at oc (index-b5774f22.js:40:39542)
```
![image](https://github.com/denkiuo604/ichitabi-timer/assets/56901711/6c7ea125-eec0-4636-99f5-f4aec46adb92)

デバッグ実行でも再現（より詳細な情報が表示された）
```
Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')
    at getDateWithPubTime (App.tsx:104:34)
    at App.tsx:138:35
    at Array.forEach (<anonymous>)
    at App.tsx:136:17
    at Array.forEach (<anonymous>)
    at getPubDateAndWeek (App.tsx:135:16)
    at App (App.tsx:21:34)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
react-dom.development.js:18687  The above error occurred in the <App> component:

    at App (http://localhost:5173/ichitabi-timer/src/App.tsx:25:29)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
その他の 1 個のフレームを表示する
簡易表示
react-dom.development.js:26923  Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')
    at getDateWithPubTime (App.tsx:104:34)
    at App.tsx:138:35
    at Array.forEach (<anonymous>)
    at App.tsx:136:17
    at Array.forEach (<anonymous>)
    at getPubDateAndWeek (App.tsx:135:16)
    at App (App.tsx:21:34)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
```
![image](https://github.com/denkiuo604/ichitabi-timer/assets/56901711/ad69b03f-8db9-4e97-bf8b-31419838216c)

**Comment by denkiuo604** [comment]
**原因**
2024年2月に第5水曜日が存在せず、次回公開日の存在しない場合が考慮されていなかったため。

**対処**
今月または来月に次回公開日が存在しなかった場合の処理を追加する。
